### ISSUE TITLE
[UI] improvements (Front & Showcase pages)

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/datahub-frontend#21]
Tasks and suggestions after UI/UX review with Sylvie (designer).

## Acceptance criteria

* [x] Front and Showcase pages look perfect

## Tasks

Front page:
* [x] typography for headings (h3) to be the same size
* [x] hero section is white, then section 1 is light grey (as on zeit) and section 2 is white again
* [x] typography for h2 - smaller
* [x] width of writings to be more narrow (Google about the best width for text readability)

Showcase page:
* [x] dates (created/updated) make it ... e.g. `3d ago` instead of ISO
* [x] format in the data package info should not be repeatative
* [x] width of writings to be more narrow (google about the best width for text readability)
* [x] remove row lines for `Field information` table
* [x] in `read me` 
  * [x] more spacing between sections
  * [x] offset gray (background) very light
  * [x] subtitles to be gray

P.S. Try to find somebody for user test...

**Comment by anuveyatsu** [comment]
FIXED in #22
